  source 'https://rubygems.org'

  gem 'selenium-webdriver'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'rake'
  gem 'headless'
  gem 'pry'
  gem 'require_all'
  gem 'yaml_extend'
  gem 'parallel_tests'
  gem 'progress_bar'
  gem 'coderay'
  gem 'activesupport'
  gem 'cucumber', '~> 3.1', '>= 3.1.2'
  gem 'allure-cucumber', "~> 0.6.1"
  gem 'capybara'
  gem 'parseconfig', '1.0.8'
  gem 'site_prism', '~> 3.4', '>= 3.4.1'
  gem 'capybara-screenshot'
  gem 'os', '~> 0.9.6'